version: "3.8"

services:
  api:
    build: ./api
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  traefik:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api

  worker:
    build: ./worker
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY
      - OPENAI_API_BASE
      - OPENAI_MODEL
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_HOST=redis
      - BASE_DIR=/data
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
